# Generated by Django 5.0.4 on 2024-08-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("article_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("abstract", models.TextField()),
                ("content", models.TextField()),
                ("published_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
