# Generated by Django 5.0.4 on 2024-07-02 02:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_department_title"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Title",
        ),
    ]
