# Generated by Django 5.0.4 on 2024-07-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0003_delete_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="age",
        ),
        migrations.AddField(
            model_name="userinfo",
            name="address",
            field=models.CharField(default="adelaide", max_length=128),
        ),
    ]
