# Generated by Django 5.0.4 on 2024-07-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0004_remove_userinfo_age_userinfo_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="address",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
