# Generated by Django 5.0.4 on 2024-07-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0005_alter_userinfo_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="age",
            field=models.IntegerField(default=18),
        ),
    ]
